process.env.NOTIFY_API_KEY = 'dummy'
process.env.NOTIFY_TEMPLATE_ID = 'dummy'
process.env.NOTIFY_REPLY_TO_ID = 'dummy'
process.env.MANAGER_URL = 'http://localhost:3009'
process.env.DESIGNER_URL = 'http://localhost:3000'
